# Generated by Django 5.2.4 on 2025-11-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoes', '0002_impressora_pedidodeimpressao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodeimpressao',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='pedidodeimpressao',
            name='frente_verso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodeimpressao',
            name='grampear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodeimpressao',
            name='quantidade_documentos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedidodeimpressao',
            name='quantidade_folhas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedidodeimpressao',
            name='tipo_impressao',
            field=models.CharField(choices=[('pb', 'Preto e Branco'), ('colorida', 'Colorida')], default='pb', max_length=20),
        ),
        migrations.CreateModel(
            name='ArquivoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/impressao/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='impressoes.pedidodeimpressao')),
            ],
        ),
    ]
